### ISSUE TITLE
init before workspace create is required with remote backends

### ISSUE THREAD

**Issue by chasebolt** [naorlivne/terraformize#15]
## Expected/Wanted Behavior
When using a fresh remote backend (gcs in my case) it should properly create the workspace.

## Actual Behavior
On the first run it will store the state in `default.tfstate`, subsequent runs it will properly store it in the `<workspace>.tfstate`

When using a remote backend (gcs), you can not run `workspace create` before `init`. Currently on the first run with a fresh backend bucket, the `workspace create` will fail and then run `init`, causing it to create a `default.tfstate` instead of `<workspace>.tfstate`. Once a `default.tfstate` has been established, on subsequent runs the `workspace create` will succeed.

## Steps to Reproduce the Problem

  1. Setup a remote backend and use example provided in README
  2. curl terraformize (creates all resources)
  3. View remote backend to see a `default.tfstate` was created instead of `<workspace>.tfstate`
  4. curl terraformize a 2nd time (creates all resources again)
  5. View remote backend to see a `<workspace>.tfstate` and a `default.tfstate`.

## Specifications
Using docker container. `FROM naorlivne/terraformize:latest`

## Logs
```
/www/terraform_modules/droplets # terraform workspace new client1
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "gcs"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Error: Initialization required. Please see the error message above.
```

**Comment by naorlivne** [comment]
I removed the init after the creation of the workspace so only a single init prior to workspace creation remains, @chasebolt mind doing a favor and ensuring that didn't regress this ticket in a way the unit test missed (you caught the last one)

**Comment by chasebolt** [comment]
i'll give it a check. right now im having issues with concurrency and locking. im using a gcs remote backend and when running multiple calls (same module, different workspace), there is high failure with errors stating lock issues.
