### ISSUE TITLE
Well done

### ISSUE THREAD

**Issue by userbradley** [naorlivne/terraformize#261]
This is not an issue, but I want to actually publically say this is awesome, and well done on creating this!

I plan to use it in the coming months!

Keep it up!

**Comment by naorlivne** [comment]
Thanks... I don't usually like keeping issues open but as this (as you said) isn't an issue I think it will stay open for a while :)

**Comment by naorlivne** [comment]
Gonna close this just due to tidying up, still appreciate the "ticket"
