### ISSUE TITLE
support for terraform validate and json output

### ISSUE THREAD

**Issue by swaroopar** [naorlivne/terraformize#451]
Hi Team, first of all thank you for this useful project. It is not a bug. Only a question from our side. 

We are currently considering using Terraformize for our project [eclipse-xpanse](https://eclipse.dev/xpanse/) as we understand that this will help us scale our application easily.
Currently from our application, we run `terraform validate -output json` to validate the module and also to return validation response in json format so that it can be parsed. 
Is there a way to achieve this using Terraformize?
Thanks again. 

## Expected/Wanted Behavior
Support for "terraform validate with json output"

## Actual Behavior
NA

## Steps to Reproduce the Problem
NA

## Specifications

Python version: 
(3.5 & higher required, lower versions may work but will not be tested against)

terraformize version: NA

OS type & version: NA

**Comment by owenwu811** [comment]
can you give a specific example?

**Comment by swaroopar** [comment]
@owenwu811 I mean this command -> https://developer.hashicorp.com/terraform/cli/commands/validate

**Comment by naorlivne** [comment]
Hi @swaroopar 

Right now Terraformize only supports plan/apply/destroy commands but adding `validate` is definitely something I'm open to, that said I can't guarantee of a time for such an addition personally, should a PR with this will be introduced I'd be more then open to accept it (hint hint).

**Comment by swaroopar** [comment]
Hi @naorlivne thank you for your positive feedback. I will give it a try and get back to you in next few days.
