### ISSUE TITLE
pyyaml version 6 not available 

### ISSUE THREAD

**Issue by owenwu811** [naorlivne/terraformize#452]
## Actual Behavior

PyYAML-6.0.tar.gz#sha256=68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2 (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_kxbgucj Check the logs for full command output.
#0 12.97 ERROR: Could not find a version that satisfies the requirement PyYAML==6.0 (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1, 6.0b1, 6.0, 6.0.1)
#0 12.97 ERROR: No matching distribution found for PyYAML==6.0
#0 13.14 WARNING: You are using pip version 21.1.2; however, version 23.2.1 is available.
#0 13.14 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
Dockerfile:26
--------------------
  24 |     
  25 |     COPY requirements.txt /www/requirements.txt
  26 | >>> RUN pip3 install --no-cache-dir -r /www/requirements.txt
  27 |     
  28 |     # copy the codebase
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir -r /www/requirements.txt" did not complete successfully: exit code: 1

## Steps to Reproduce the Problem

build the docker file 

## Specifications

Python version: 
PyYAML-6.0.tar.gz#sha256=68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2 (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp_kxbgucj Check the logs for full command output.
#0 12.97 ERROR: Could not find a version that satisfies the requirement PyYAML==6.0 (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1, 3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1, 5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1, 6.0b1, 6.0, 6.0.1)
#0 12.97 ERROR: No matching distribution found for PyYAML==6.0
#0 13.14 WARNING: You are using pip version 21.1.2; however, version 23.2.1 is available.
#0 13.14 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
Dockerfile:26
--------------------
  24 |     
  25 |     COPY requirements.txt /www/requirements.txt
  26 | >>> RUN pip3 install --no-cache-dir -r /www/requirements.txt
  27 |     
  28 |     # copy the codebase
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir -r /www/requirements.txt" did not complete successfully: exit code: 1

**Comment by naorlivne** [comment]
My guess is your using an old version of the repo, this was already fixed in locking `PyYAML==6.0.1` in the `requirements.txt` file

**Comment by owenwu811** [comment]
Thank you!
