### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by UriKatsirPrivate** [naorlivne/terraformize#47]
## Expected/Wanted Behavior
Apply terraform files

## Actual Behavior
500 Internal Server Error

## Steps to Reproduce the Problem

  1. Followed the instructions
  2.
  3.

## Specifications

Python version: 
(3.5 & higher required, lower versions may work but will not be tested against)
3.7.5
terraformize version:
latest
OS type & version:
Mac Catalina 10.15.2

**Comment by naorlivne** [comment]
Retried the example provided in the readme & can confirm it working.

Please provide more details.

- By `Followed the instructions` do you mean you follow the example provided in the readme or something else?
- At what step are you getting 500 error?
- Are you running the prebuilt docker container or by cloning the repo?
- What configuration options are you using?

**Comment by UriKatsirPrivate** [comment]
Hi,

Thanks for the quick reply:

1. Yes, I followed the example provided in the readme.
2. I am getting the 500 error when I try to perform a POST operation. The GET operation is successful.
3. I did not clone the repo, I run the "docker run" (Step #3) command that is in the Example steps.
4. No configuration, I run the curl command as it appears in step #4 of the example and I get the 500 error.

Thank you

**Comment by naorlivne** [comment]
Hi,

did you create `terraformize_test/test.tf` in step 2 with a vaild config & mounted it into the container? 

if the answer is yes are you acccessing the correct folder name in your POST requests (`terraformize_test` in the readme example)?

**Comment by UriKatsirPrivate** [comment]
Hi,

Yes, I created terraformize_test/test.tf file with a valid config and mounted it to the container. Please see attached image of the folder structure on the container. (https://storage.googleapis.com/artifacts.uri-test.appspot.com/folders.png)

With this folder structure, The URL I am accessing is "http://127.0.0.1/v1/terraformize_test/" and this time getting a 404 error.

Thanks

Uri

**Comment by naorlivne** [comment]
you need to access something like `http://127.0.0.1/v1/terraformize_test/my_workspace` - the `my_workspace` part of the link is required even if you only want to use a single workspace (you can just pass `default` or whatever name you wish in that case as long as in all requests you pass the same name)

**Comment by UriKatsirPrivate** [comment]
Thanks, it works now.

**Comment by naorlivne** [comment]
NP
