### ISSUE TITLE
Credentials for GCP provider

### ISSUE THREAD

**Issue by UriKatsirPrivate** [naorlivne/terraformize#48]
## Expected/Wanted Behavior
Run terraform with a GCP provider

## Actual Behavior
The GCP provider is unable to authenticate and I get an error message "could not find default credentials" 

## Steps to Reproduce the Problem

  1.Use GCP provider in a tf file
  2.Execute a POST command
  3.

## Specifications
I have a "connections.tf" file in my module that points to a credentials file located on the container. When I run POST using the api, it fails with the error message above.
When I ssh to the container and execute "terraform init" locally, I get the same error message.
To try and workaround this, I run "export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"" locally on the container and I am able to execute "terraform init" locally. But the REST call still fails with the same error message.
Python version: 
(3.5 & higher required, lower versions may work but will not be tested against)
Python 3.7.5
terraformize version:
latest
OS type & version:
Mac Catalina Version 10.15.2

**Comment by naorlivne** [comment]
This isn't a Terraformize but rather an issue to configure GCP provider to work with Terraform so gonna close this.

That said I'm guessing (and this is just a guess, again can't really assist further) that you need to configure some envvars the GCP provider requires when you start the container and\or configure credentials as part of your terraform module.
